# Generated by Django 6.1 on 2026-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('COACH', 'Coach')], max_length=10),
        ),
    ]
